### ISSUE TITLE
Could you add a result filter?

### ISSUE THREAD

**Issue by Hua-CM** [labstructbioinf/DeepCoil#1]
I‘d like to appriciate your work here. However, since this software does not provide an exact result whether a sequence has a CC domain(I understand there was not a common standard), I advice that you could add a result filter.
  I had read your paper. I think your definitian method in paper can be used as reference to other cases. So the result filter may include two arguments：
（i） the number of consecutive residues had greater score than a artificial score
（ii）the artificial score mentioned above

**Comment by labstructbioinf** [comment]
We added two options (`-min_segment_length` and `--min_residue_score`) that implement the requested functionality.
