### ISSUE TITLE
seqvec.zip

### ISSUE THREAD

**Issue by PetrAdamek440** [labstructbioinf/DeepCoil#11]
If I downloaded the seqvec.zip file from https://lbs.cent.uw.edu.pl/static/files/seqvec.zip, 
is there any possibility to make deepcoil to take this file from HDD not while running a script in Python3 ?
(The last way takes really a very long time and it seems to me that it can interrupt by itself.) Thanks.

**Comment by jludwiczak** [comment]
Hello Petr,
The `seqvec.zip` (weights of the SeqVec model) file is downloaded automatically during the first use of DeepCoil2. We provide two links embedded within the code - one is the original website of the authors and the other is a mirror hosted in our lab. If you want to run DeepCoil2 on the machine without internet connection you can look at the relevant part of code - https://github.com/labstructbioinf/DeepCoil/blob/master/deepcoil/deepcoil.py#L56-L75 - and put the seqvec.zip contents in the appropriate location manually. Hope this'll be helpful.
