### ISSUE TITLE
DeepCoil2, reference 

### ISSUE THREAD

**Issue by bulak** [labstructbioinf/DeepCoil#16]
Hello,

The changes you have introduced into your algorithm with the new v2 are indeed very appealing: no more 500 aa limit, faster predictions without using PSI-Blast. Thank you very much!
However, I have noted in few proteins, the difference between the outputs from the first version (with PSI-Blast) and the second version is quite notable. Not a thorough comparison but so far it seems the differences occur mostly on estimates of non-canonical coiled-coil structures. Do you have a publication/pre-print/blog/dataset to which we can refer to in order to understand exactly this new version is performing and also which we can cite if we use DeepCoil2 in our research?

**Comment by staszekdh** [comment]
Hi, we are interested in the prediction of non-canonical coiled coils, thus your observations are very interesting. Please contact us by email, so we can discuss it and share with you the draft of the DC2 paper.
