### ISSUE TITLE
Issues running the script

### ISSUE THREAD

**Issue by RobertHaJa** [labstructbioinf/DeepCoil#17]
Hello!

I am very much a novice when it comes to python scripts, but I've tried running it natively on my Windows 10 OS, Anaconda3 and finally an Ubuntu VM. It always ended up with the same problem when I am trying to run the .py file in "site-packages".

`robert@DESKTOP-BBS6TCM:~/.local/lib/python3.8/site-packages/deepcoil$ python3 deepcoil.py
Traceback (most recent call last):
  File "deepcoil.py", line 9, in <module>
    from deepcoil.utils.seqvec import SeqVec
  File "/home/robert/.local/lib/python3.8/site-packages/deepcoil/deepcoil.py", line 9, in <module>
    from deepcoil.utils.seqvec import SeqVec
ModuleNotFoundError: No module named 'deepcoil.utils'; 'deepcoil' is not a package`

Care to shed any light on what I might be doing incorrectly? Is there something incorrectly named?

Thanks in advance,
Robert

**Comment by RobertHaJa** [comment]
I have resolved the issue, I realise I was calling the module incorrectly. Ergo - "python3 deepcoil.py" and not just "deepcoil". 

I had a bunch of other issues with incompatible versions, but downgrading them version by version got the program running for me in the end.

**Comment by 404-xianjin** [comment]
@RobertHaJa hi，Will this program work under windows operating system?
