### ISSUE TITLE
Can't install Spacy==2.1.9

### ISSUE THREAD

**Issue by BZhao716** [labstructbioinf/DeepCoil#20]
When I run pip3 install deepcoil, it always came with 
"Collecting spacy<2.2,>=2.1.0
  Using cached spacy-2.1.9.tar.gz (30.7 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1"

I tried to fix with update wheel, install blis, install spacy-2.1.0 before install deepcoil. It didn't work. Is there any way to solve it?

**Comment by jludwiczak** [comment]
Hi @BZhao716 - to confirm - are you using `pip>=19.0` and python 3.7 or 3.8?
