### ISSUE TITLE
Subprocess build dependencies error

### ISSUE THREAD

**Issue by brendankz** [labstructbioinf/DeepCoil#21]
Hi, I recently received the following error message trying to download DeepCoil through the pip3 command:

$ pip3 install deepcoil
Collecting deepcoil
  Using cached deepcoil-2.0.2-py2.py3-none-any.whl (100.4 MB)
Collecting allennlp==0.9.0 (from deepcoil)
  Using cached allennlp-0.9.0-py3-none-any.whl (7.6 MB)
Requirement already satisfied: biopython==1.79 in /data/home/bsk74/miniconda3/envs/Deepcoil/lib/python3.8/site-packages (from deepcoil) (1.79)
Requirement already satisfied: overrides==3.1.0 in /data/home/bsk74/miniconda3/envs/Deepcoil/lib/python3.8/site-packages (from deepcoil) (3.1.0)
Requirement already satisfied: pandas==1.3.0 in /data/home/bsk74/miniconda3/envs/Deepcoil/lib/python3.8/site-packages (from deepcoil) (1.3.0)
Collecting seaborn<0.13.0,>=0.12.0 (from deepcoil)
  Using cached seaborn-0.12.2-py3-none-any.whl (293 kB)
Collecting tensorflow<3.0,>=2.3 (from deepcoil)
  Using cached tensorflow-2.12.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (585.9 MB)
Collecting torch>=1.2.0 (from allennlp==0.9.0->deepcoil)
  Using cached torch-2.0.1-cp38-cp38-manylinux1_x86_64.whl (619.9 MB)
Collecting nltk (from allennlp==0.9.0->deepcoil)
  Using cached nltk-3.8.1-py3-none-any.whl (1.5 MB)
Collecting spacy<2.2,>=2.1.0 (from allennlp==0.9.0->deepcoil)
  Using cached spacy-2.1.9.tar.gz (30.7 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [273 lines of output]
      Collecting setuptools
        Using cached setuptools-68.0.0-py3-none-any.whl (804 kB)
      Collecting wheel<0.33.0,>0.32.0
        Using cached wheel-0.32.3-py2.py3-none-any.whl (21 kB)
      Collecting Cython
        Using cached Cython-0.29.35-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (2.0 MB)
      Collecting cymem<2.1.0,>=2.0.2
        Using cached cymem-2.0.7-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (36 kB)
      Collecting preshed<2.1.0,>=2.0.1
        Using cached preshed-2.0.1.tar.gz (113 kB)
        Preparing metadata (setup.py): started
        Preparing metadata (setup.py): finished with status 'done'
      Collecting murmurhash<1.1.0,>=0.28.0
        Using cached murmurhash-1.0.9-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (21 kB)
      Collecting thinc<7.1.0,>=7.0.8
        Using cached thinc-7.0.8.tar.gz (1.9 MB)
        Preparing metadata (setup.py): started
        Preparing metadata (setup.py): finished with status 'done'
      Collecting blis<0.3.0,>=0.2.1 (from thinc<7.1.0,>=7.0.8)
        Using cached blis-0.2.4-cp38-cp38-linux_x86_64.whl
      Collecting wasabi<1.1.0,>=0.0.9 (from thinc<7.1.0,>=7.0.8)
        Using cached wasabi-0.10.1-py3-none-any.whl (26 kB)
      Collecting srsly<1.1.0,>=0.0.6 (from thinc<7.1.0,>=7.0.8)
        Using cached srsly-1.0.6-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (211 kB)
      Collecting numpy>=1.7.0 (from thinc<7.1.0,>=7.0.8)
        Using cached numpy-1.24.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
      Collecting plac<1.0.0,>=0.9.6 (from thinc<7.1.0,>=7.0.8)
        Using cached plac-0.9.6-py2.py3-none-any.whl (20 kB)
      Collecting tqdm<5.0.0,>=4.10.0 (from thinc<7.1.0,>=7.0.8)
        Using cached tqdm-4.65.0-py3-none-any.whl (77 kB)
      Building wheels for collected packages: preshed, thinc
        Building wheel for preshed (setup.py): started
        Building wheel for preshed (setup.py): finished with status 'error'
        error: subprocess-exited-with-error
      
        × python setup.py bdist_wheel did not run successfully.
        │ exit code: 1
        ╰─> [35 lines of output]
            /home/miniconda3/envs/Deepcoil/lib/python3.8/site-packages/setuptools/__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
            !!
      
                    ********************************************************************************
                    Requirements should be satisfied by a PEP 517 installer.
                    If you are using pip, you can try `pip install --use-pep517`.
                    ********************************************************************************
      
            !!
              dist.fetch_build_eggs(dist.setup_requires)
            running bdist_wheel
            running build
            running build_py
            creating build
            creating build/lib.linux-x86_64-cpython-38
            creating build/lib.linux-x86_64-cpython-38/preshed
            copying preshed/about.py -> build/lib.linux-x86_64-cpython-38/preshed
            copying preshed/__init__.py -> build/lib.linux-x86_64-cpython-38/preshed
            creating build/lib.linux-x86_64-cpython-38/preshed/tests
            copying preshed/tests/test_pop.py -> build/lib.linux-x86_64-cpython-38/preshed/tests
            copying preshed/tests/test_hashing.py -> build/lib.linux-x86_64-cpython-38/preshed/tests
            copying preshed/tests/__init__.py -> build/lib.linux-x86_64-cpython-38/preshed/tests
            copying preshed/tests/test_counter.py -> build/lib.linux-x86_64-cpython-38/preshed/tests
            copying preshed/maps.pyx -> build/lib.linux-x86_64-cpython-38/preshed
            copying preshed/counter.pyx -> build/lib.linux-x86_64-cpython-38/preshed
            copying preshed/maps.pxd -> build/lib.linux-x86_64-cpython-38/preshed
            copying preshed/counter.pxd -> build/lib.linux-x86_64-cpython-38/preshed
            copying preshed/__init__.pxd -> build/lib.linux-x86_64-cpython-38/preshed
            running build_ext
            building 'preshed.maps' extension
            creating build/temp.linux-x86_64-cpython-38
            creating build/temp.linux-x86_64-cpython-38/preshed
            gcc -pthread -B /home/miniconda3/envs/Deepcoil/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/bsk74/miniconda3/envs/Deepcoil/include/python3.8 -I/home/bsk74/miniconda3/envs/Deepcoil/include/python3.8 -c preshed/maps.cpp -o build/temp.linux-x86_64-cpython-38/preshed/maps.o -O3 -Wno-strict-prototypes -Wno-unused-function
            gcc: error trying to exec 'cc1plus': execvp: No such file or directory
            error: command '/usr/bin/gcc' failed with exit code 1
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for preshed
        Running setup.py clean for preshed
        Building wheel for thinc (setup.py): started
        Building wheel for thinc (setup.py): finished with status 'error'
        error: subprocess-exited-with-error
      
        × python setup.py bdist_wheel did not run successfully.
        │ exit code: 1
        ╰─> [181 lines of output]
            /home/miniconda3/envs/Deepcoil/lib/python3.8/site-packages/setuptools/__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
            !!
      
                    ********************************************************************************
                    Requirements should be satisfied by a PEP 517 installer.
                    If you are using pip, you can try `pip install --use-pep517`.
                    ********************************************************************************
      
            !!
              dist.fetch_build_eggs(dist.setup_requires)
            running bdist_wheel
            running build
            running build_py
            creating build
            creating build/lib.linux-x86_64-cpython-38
            creating build/lib.linux-x86_64-cpython-38/thinc
            copying thinc/t2t.py -> build/lib.linux-x86_64-cpython-38/thinc
            copying thinc/rates.py -> build/lib.linux-x86_64-cpython-38/thinc
            copying thinc/about.py -> build/lib.linux-x86_64-cpython-38/thinc
            copying thinc/i2v.py -> build/lib.linux-x86_64-cpython-38/thinc
            copying thinc/check.py -> build/lib.linux-x86_64-cpython-38/thinc
            copying thinc/compat.py -> build/lib.linux-x86_64-cpython-38/thinc
            copying thinc/describe.py -> build/lib.linux-x86_64-cpython-38/thinc
            copying thinc/loss.py -> build/lib.linux-x86_64-cpython-38/thinc
            copying thinc/misc.py -> build/lib.linux-x86_64-cpython-38/thinc
            copying thinc/__init__.py -> build/lib.linux-x86_64-cpython-38/thinc
            copying thinc/exceptions.py -> build/lib.linux-x86_64-cpython-38/thinc
            copying thinc/api.py -> build/lib.linux-x86_64-cpython-38/thinc
            copying thinc/v2v.py -> build/lib.linux-x86_64-cpython-38/thinc
            copying thinc/t2v.py -> build/lib.linux-x86_64-cpython-38/thinc
            creating build/lib.linux-x86_64-cpython-38/thinc/tests
            copying thinc/tests/strategies.py -> build/lib.linux-x86_64-cpython-38/thinc/tests
            copying thinc/tests/conftest.py -> build/lib.linux-x86_64-cpython-38/thinc/tests
            copying thinc/tests/test_api_funcs.py -> build/lib.linux-x86_64-cpython-38/thinc/tests
            copying thinc/tests/util.py -> build/lib.linux-x86_64-cpython-38/thinc/tests
            copying thinc/tests/test_util.py -> build/lib.linux-x86_64-cpython-38/thinc/tests
            copying thinc/tests/__init__.py -> build/lib.linux-x86_64-cpython-38/thinc/tests
            creating build/lib.linux-x86_64-cpython-38/thinc/tests/unit
            copying thinc/tests/unit/test_ops.py -> build/lib.linux-x86_64-cpython-38/thinc/tests/unit
            copying thinc/tests/unit/test_rates.py -> build/lib.linux-x86_64-cpython-38/thinc/tests/unit
            copying thinc/tests/unit/test_rnn.py -> build/lib.linux-x86_64-cpython-38/thinc/tests/unit
            copying thinc/tests/unit/test_pickle.py -> build/lib.linux-x86_64-cpython-38/thinc/tests/unit
            copying thinc/tests/unit/test_beam_search.py -> build/lib.linux-x86_64-cpython-38/thinc/tests/unit
            copying thinc/tests/unit/test_hash_embed.py -> build/lib.linux-x86_64-cpython-38/thinc/tests/unit
            copying thinc/tests/unit/test_about.py -> build/lib.linux-x86_64-cpython-38/thinc/tests/unit
            copying thinc/tests/unit/test_difference.py -> build/lib.linux-x86_64-cpython-38/thinc/tests/unit
            copying thinc/tests/unit/test_mem.py -> build/lib.linux-x86_64-cpython-38/thinc/tests/unit
            copying thinc/tests/unit/test_affine.py -> build/lib.linux-x86_64-cpython-38/thinc/tests/unit
            copying thinc/tests/unit/test_linear.py -> build/lib.linux-x86_64-cpython-38/thinc/tests/unit
            copying thinc/tests/unit/test_check_exceptions.py -> build/lib.linux-x86_64-cpython-38/thinc/tests/unit
            copying thinc/tests/unit/test_pytorch_wrapper.py -> build/lib.linux-x86_64-cpython-38/thinc/tests/unit
            copying thinc/tests/unit/test_imports.py -> build/lib.linux-x86_64-cpython-38/thinc/tests/unit
            copying thinc/tests/unit/test_feature_extracter.py -> build/lib.linux-x86_64-cpython-38/thinc/tests/unit
            copying thinc/tests/unit/__init__.py -> build/lib.linux-x86_64-cpython-38/thinc/tests/unit
            copying thinc/tests/unit/test_pooling.py -> build/lib.linux-x86_64-cpython-38/thinc/tests/unit
            copying thinc/tests/unit/test_model.py -> build/lib.linux-x86_64-cpython-38/thinc/tests/unit
            copying thinc/tests/unit/test_loss.py -> build/lib.linux-x86_64-cpython-38/thinc/tests/unit
            creating build/lib.linux-x86_64-cpython-38/thinc/tests/integration
            copying thinc/tests/integration/test_mnist.py -> build/lib.linux-x86_64-cpython-38/thinc/tests/integration
            copying thinc/tests/integration/test_affine_learns.py -> build/lib.linux-x86_64-cpython-38/thinc/tests/integration
            copying thinc/tests/integration/test_pickle.py -> build/lib.linux-x86_64-cpython-38/thinc/tests/integration
            copying thinc/tests/integration/test_basic_tagger.py -> build/lib.linux-x86_64-cpython-38/thinc/tests/integration
            copying thinc/tests/integration/test_feed_forward.py -> build/lib.linux-x86_64-cpython-38/thinc/tests/integration
            copying thinc/tests/integration/__init__.py -> build/lib.linux-x86_64-cpython-38/thinc/tests/integration
            copying thinc/tests/integration/test_batch_norm.py -> build/lib.linux-x86_64-cpython-38/thinc/tests/integration
            copying thinc/tests/integration/test_shape_check.py -> build/lib.linux-x86_64-cpython-38/thinc/tests/integration
            copying thinc/tests/integration/test_roundtrip_bytes.py -> build/lib.linux-x86_64-cpython-38/thinc/tests/integration
            creating build/lib.linux-x86_64-cpython-38/thinc/tests/linear
            copying thinc/tests/linear/test_avgtron.py -> build/lib.linux-x86_64-cpython-38/thinc/tests/linear
            copying thinc/tests/linear/test_linear.py -> build/lib.linux-x86_64-cpython-38/thinc/tests/linear
            copying thinc/tests/linear/test_sparse_array.py -> build/lib.linux-x86_64-cpython-38/thinc/tests/linear
            copying thinc/tests/linear/__init__.py -> build/lib.linux-x86_64-cpython-38/thinc/tests/linear
            creating build/lib.linux-x86_64-cpython-38/thinc/linear
            copying thinc/linear/__init__.py -> build/lib.linux-x86_64-cpython-38/thinc/linear
            creating build/lib.linux-x86_64-cpython-38/thinc/neural
            copying thinc/neural/_lsuv.py -> build/lib.linux-x86_64-cpython-38/thinc/neural
            copying thinc/neural/train.py -> build/lib.linux-x86_64-cpython-38/thinc/neural
            copying thinc/neural/util.py -> build/lib.linux-x86_64-cpython-38/thinc/neural
            copying thinc/neural/vec2vec.py -> build/lib.linux-x86_64-cpython-38/thinc/neural
            copying thinc/neural/__init__.py -> build/lib.linux-x86_64-cpython-38/thinc/neural
            copying thinc/neural/mem.py -> build/lib.linux-x86_64-cpython-38/thinc/neural
            copying thinc/neural/vecs2vec.py -> build/lib.linux-x86_64-cpython-38/thinc/neural
            copying thinc/neural/vecs2vecs.py -> build/lib.linux-x86_64-cpython-38/thinc/neural
            copying thinc/neural/pooling.py -> build/lib.linux-x86_64-cpython-38/thinc/neural
            creating build/lib.linux-x86_64-cpython-38/thinc/extra
            copying thinc/extra/datasets.py -> build/lib.linux-x86_64-cpython-38/thinc/extra
            copying thinc/extra/load_nlp.py -> build/lib.linux-x86_64-cpython-38/thinc/extra
            copying thinc/extra/visualizer.py -> build/lib.linux-x86_64-cpython-38/thinc/extra
            copying thinc/extra/__init__.py -> build/lib.linux-x86_64-cpython-38/thinc/extra
            copying thinc/extra/hpbff.py -> build/lib.linux-x86_64-cpython-38/thinc/extra
            copying thinc/extra/wrappers.py -> build/lib.linux-x86_64-cpython-38/thinc/extra
            creating build/lib.linux-x86_64-cpython-38/thinc/neural/_classes
            copying thinc/neural/_classes/difference.py -> build/lib.linux-x86_64-cpython-38/thinc/neural/_classes
            copying thinc/neural/_classes/feature_extracter.py -> build/lib.linux-x86_64-cpython-38/thinc/neural/_classes
            copying thinc/neural/_classes/relu.py -> build/lib.linux-x86_64-cpython-38/thinc/neural/_classes
            copying thinc/neural/_classes/hash_embed.py -> build/lib.linux-x86_64-cpython-38/thinc/neural/_classes
            copying thinc/neural/_classes/encoder_decoder.py -> build/lib.linux-x86_64-cpython-38/thinc/neural/_classes
            copying thinc/neural/_classes/multiheaded_attention.py -> build/lib.linux-x86_64-cpython-38/thinc/neural/_classes
            copying thinc/neural/_classes/rnn.py -> build/lib.linux-x86_64-cpython-38/thinc/neural/_classes
            copying thinc/neural/_classes/feed_forward.py -> build/lib.linux-x86_64-cpython-38/thinc/neural/_classes
            copying thinc/neural/_classes/embed.py -> build/lib.linux-x86_64-cpython-38/thinc/neural/_classes
            copying thinc/neural/_classes/elu.py -> build/lib.linux-x86_64-cpython-38/thinc/neural/_classes
            copying thinc/neural/_classes/model.py -> build/lib.linux-x86_64-cpython-38/thinc/neural/_classes
            copying thinc/neural/_classes/layernorm.py -> build/lib.linux-x86_64-cpython-38/thinc/neural/_classes
            copying thinc/neural/_classes/static_vectors.py -> build/lib.linux-x86_64-cpython-38/thinc/neural/_classes
            copying thinc/neural/_classes/affine.py -> build/lib.linux-x86_64-cpython-38/thinc/neural/_classes
            copying thinc/neural/_classes/function_layer.py -> build/lib.linux-x86_64-cpython-38/thinc/neural/_classes
            copying thinc/neural/_classes/__init__.py -> build/lib.linux-x86_64-cpython-38/thinc/neural/_classes
            copying thinc/neural/_classes/selu.py -> build/lib.linux-x86_64-cpython-38/thinc/neural/_classes
            copying thinc/neural/_classes/batchnorm.py -> build/lib.linux-x86_64-cpython-38/thinc/neural/_classes
            copying thinc/neural/_classes/maxout.py -> build/lib.linux-x86_64-cpython-38/thinc/neural/_classes
            copying thinc/neural/_classes/attention.py -> build/lib.linux-x86_64-cpython-38/thinc/neural/_classes
            copying thinc/neural/_classes/resnet.py -> build/lib.linux-x86_64-cpython-38/thinc/neural/_classes
            copying thinc/neural/_classes/softmax.py -> build/lib.linux-x86_64-cpython-38/thinc/neural/_classes
            copying thinc/neural/_classes/convolution.py -> build/lib.linux-x86_64-cpython-38/thinc/neural/_classes
            creating build/lib.linux-x86_64-cpython-38/thinc/extra/_vendorized
            copying thinc/extra/_vendorized/keras_data_utils.py -> build/lib.linux-x86_64-cpython-38/thinc/extra/_vendorized
            copying thinc/extra/_vendorized/__init__.py -> build/lib.linux-x86_64-cpython-38/thinc/extra/_vendorized
            copying thinc/extra/_vendorized/keras_generic_utils.py -> build/lib.linux-x86_64-cpython-38/thinc/extra/_vendorized
            copying thinc/extra/_vendorized/keras_datasets.py -> build/lib.linux-x86_64-cpython-38/thinc/extra/_vendorized
            creating build/lib.linux-x86_64-cpython-38/thinc/extra/wrapt
            copying thinc/extra/wrapt/importer.py -> build/lib.linux-x86_64-cpython-38/thinc/extra/wrapt
            copying thinc/extra/wrapt/__init__.py -> build/lib.linux-x86_64-cpython-38/thinc/extra/wrapt
            copying thinc/extra/wrapt/decorators.py -> build/lib.linux-x86_64-cpython-38/thinc/extra/wrapt
            copying thinc/extra/wrapt/wrappers.py -> build/lib.linux-x86_64-cpython-38/thinc/extra/wrapt
            copying thinc/linalg.pyx -> build/lib.linux-x86_64-cpython-38/thinc
            copying thinc/typedefs.pyx -> build/lib.linux-x86_64-cpython-38/thinc
            copying thinc/structs.pyx -> build/lib.linux-x86_64-cpython-38/thinc
            copying thinc/cpu.pxd -> build/lib.linux-x86_64-cpython-38/thinc
            copying thinc/structs.pxd -> build/lib.linux-x86_64-cpython-38/thinc
            copying thinc/linalg.pxd -> build/lib.linux-x86_64-cpython-38/thinc
            copying thinc/__init__.pxd -> build/lib.linux-x86_64-cpython-38/thinc
            copying thinc/typedefs.pxd -> build/lib.linux-x86_64-cpython-38/thinc
            copying thinc/compile_time_constants.pxi -> build/lib.linux-x86_64-cpython-38/thinc
            copying thinc/linalg.cpp -> build/lib.linux-x86_64-cpython-38/thinc
            copying thinc/typedefs.cpp -> build/lib.linux-x86_64-cpython-38/thinc
            copying thinc/structs.cpp -> build/lib.linux-x86_64-cpython-38/thinc
            copying thinc/linear/serialize.pyx -> build/lib.linux-x86_64-cpython-38/thinc/linear
            copying thinc/linear/avgtron.pyx -> build/lib.linux-x86_64-cpython-38/thinc/linear
            copying thinc/linear/features.pyx -> build/lib.linux-x86_64-cpython-38/thinc/linear
            copying thinc/linear/linear.pyx -> build/lib.linux-x86_64-cpython-38/thinc/linear
            copying thinc/linear/sparse.pyx -> build/lib.linux-x86_64-cpython-38/thinc/linear
            copying thinc/linear/sparse.pxd -> build/lib.linux-x86_64-cpython-38/thinc/linear
            copying thinc/linear/features.pxd -> build/lib.linux-x86_64-cpython-38/thinc/linear
            copying thinc/linear/avgtron.pxd -> build/lib.linux-x86_64-cpython-38/thinc/linear
            copying thinc/linear/serialize.pxd -> build/lib.linux-x86_64-cpython-38/thinc/linear
            copying thinc/linear/__init__.pxd -> build/lib.linux-x86_64-cpython-38/thinc/linear
            copying thinc/linear/serialize.cpp -> build/lib.linux-x86_64-cpython-38/thinc/linear
            copying thinc/linear/avgtron.cpp -> build/lib.linux-x86_64-cpython-38/thinc/linear
            copying thinc/linear/sparse.cpp -> build/lib.linux-x86_64-cpython-38/thinc/linear
            copying thinc/linear/linear.cpp -> build/lib.linux-x86_64-cpython-38/thinc/linear
            copying thinc/linear/features.cpp -> build/lib.linux-x86_64-cpython-38/thinc/linear
            copying thinc/neural/optimizers.pyx -> build/lib.linux-x86_64-cpython-38/thinc/neural
            copying thinc/neural/_aligned_alloc.pyx -> build/lib.linux-x86_64-cpython-38/thinc/neural
            copying thinc/neural/ops.pyx -> build/lib.linux-x86_64-cpython-38/thinc/neural
            copying thinc/neural/cpu.pxd -> build/lib.linux-x86_64-cpython-38/thinc/neural
            copying thinc/neural/ops.pxd -> build/lib.linux-x86_64-cpython-38/thinc/neural
            copying thinc/neural/__init__.pxd -> build/lib.linux-x86_64-cpython-38/thinc/neural
            copying thinc/neural/_aligned_alloc.cpp -> build/lib.linux-x86_64-cpython-38/thinc/neural
            copying thinc/neural/optimizers.cpp -> build/lib.linux-x86_64-cpython-38/thinc/neural
            copying thinc/neural/ops.cpp -> build/lib.linux-x86_64-cpython-38/thinc/neural
            copying thinc/extra/eg.pyx -> build/lib.linux-x86_64-cpython-38/thinc/extra
            copying thinc/extra/mb.pyx -> build/lib.linux-x86_64-cpython-38/thinc/extra
            copying thinc/extra/search.pyx -> build/lib.linux-x86_64-cpython-38/thinc/extra
            copying thinc/extra/cache.pyx -> build/lib.linux-x86_64-cpython-38/thinc/extra
            copying thinc/extra/cache.pxd -> build/lib.linux-x86_64-cpython-38/thinc/extra
            copying thinc/extra/search.pxd -> build/lib.linux-x86_64-cpython-38/thinc/extra
            copying thinc/extra/eg.pxd -> build/lib.linux-x86_64-cpython-38/thinc/extra
            copying thinc/extra/mb.pxd -> build/lib.linux-x86_64-cpython-38/thinc/extra
            copying thinc/extra/__init__.pxd -> build/lib.linux-x86_64-cpython-38/thinc/extra
            copying thinc/extra/mb.cpp -> build/lib.linux-x86_64-cpython-38/thinc/extra
            copying thinc/extra/search.cpp -> build/lib.linux-x86_64-cpython-38/thinc/extra
            copying thinc/extra/cache.cpp -> build/lib.linux-x86_64-cpython-38/thinc/extra
            copying thinc/extra/eg.cpp -> build/lib.linux-x86_64-cpython-38/thinc/extra
            running build_ext
            building 'thinc.linalg' extension
            creating build/temp.linux-x86_64-cpython-38
            creating build/temp.linux-x86_64-cpython-38/thinc
            gcc -pthread -B /home/miniconda3/envs/Deepcoil/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/bsk74/miniconda3/envs/Deepcoil/include/python3.8 -I/tmp/pip-install-ywz44zz4/thinc_7e2252b047d94da7a3f1f46133b7fbf3/include -I/home/bsk74/miniconda3/envs/Deepcoil/include/python3.8 -c thinc/linalg.cpp -o build/temp.linux-x86_64-cpython-38/thinc/linalg.o -O3 -Wno-strict-prototypes -Wno-unused-function
            gcc: error trying to exec 'cc1plus': execvp: No such file or directory
            error: command '/usr/bin/gcc' failed with exit code 1
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for thinc
        Running setup.py clean for thinc
      Failed to build preshed thinc
      ERROR: Could not build wheels for preshed, thinc, which is required to install pyproject.toml-based projects
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by jludwiczak** [comment]
Moved to e-mail communication and solved (proper GCC setup was needed).
