### ISSUE TITLE
Whether Windows is supported

### ISSUE THREAD

**Issue by 404-xianjin** [labstructbioinf/DeepCoil#22]
As of August 14, 2023, does DeepCoil version 2.0.2 support Windows os？
Thank you。

**Comment by 404-xianjin** [comment]
@jludwiczak

**Comment by 404-xianjin** [comment]
@staszekdh

**Comment by jludwiczak** [comment]
Hello @404-xianjin, thanks for interest in our tool. 
Currently we don't support Windows, I may suggest installing VM or trying with WSL2 subspace on Windows. Hope this'll be helpful!
