### ISSUE TITLE
500 aminoacid limitation

### ISSUE THREAD

**Issue by bulak** [labstructbioinf/DeepCoil#4]
Great tool, thanks! 

One thing that frequently breaks my analysis pipeline is the upper limit on the sequence length: 500 aa. 

Do you think it would be appropriate to split a protein sequence that is larger than 500 aa into possibly overlapping 500 aa long chunks, process the chunks with deepcoil and then stitch back the output of individual chunks into a single one? Are there any red flags against this approach?

What is your recommendation? 

Many thanks.

**Comment by labstructbioinf** [comment]
Hi, thanks for your interest in our tool!

I think the approach you propose is reasonable. Before averaging the overlapping parts of the chunks, I would check whether the per-residue predictions are similar.

Staszek

**Comment by jludwiczak** [comment]
Hey, to give an update on the issue - the 500 aa limit will be fixed in the upcoming release. DeepCoil will accept sequences of any length. I'm closing this issue for now.
